#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for lcm
#
# IDENTIFICATION
#    src/backend/optimizer/lcm/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/lcm
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	lcm_extension.o

include $(top_srcdir)/src/backend/common.mk
